#!/bin/bash

cd "$(dirname "$0")/.."

set -e

PROJECT_DISPLAY_NAME="Endpoints"

echo "--- [$PROJECT_DISPLAY_NAME] Bootstrapping dependencies"
if hash carthage 2>/dev/null
then
    carthage bootstrap --no-use-binaries --platform ios
else
    echo "Error: Carthage must be installed."
    exit 1
fi
